# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on: [push]

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm install
      - run: npm test

  build-app:
    runs-on: ubuntu-latest
    needs: test-app

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install, Test and Build
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: |
          npm install
          npm test
          npm run build

      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build/

  deploy-app:
    runs-on: ubuntu-latest
    needs: build-app

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Get Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Deployment
        run: npm install -g netlify-cli

      - name: Attatch
        env:
          NETLIFY_AUTH_TOKEN: _Ew2-Msnv91fJshNg8yGZ-8uewWM95A8C5KAD3t5iLw
          NETLIFY_SITE_ID: 0ac98577-98bb-4112-8cce-07db033bbd20
        run: netlify deploy --dir=build --prod
